package ifneeded Metawidget 1.3 "
  source \"[file join [set dir] metawidget.tcl]\"
"

package ifneeded mkWidgets 1.3 "
  source \"[file join [set dir] Tooltip.tcl]\"
  source \"[file join [set dir] Calendar.tcl]\"
  source \"[file join [set dir] Aclock.tcl]\"
  source \"[file join [set dir] Combobox.tcl]\"
  source \"[file join [set dir] Scrollbox.tcl]\"
  source \"[file join [set dir] Toolbar.tcl]\"
  source \"[file join [set dir] Statusbar.tcl]\"
  source \"[file join [set dir] Textframe.tcl]\"
  source \"[file join [set dir] Window.tcl]\"
  source \"[file join [set dir] Document.tcl]\"
  source \"[file join [set dir] Pane.tcl]\"
  source \"[file join [set dir] Tabcontrol.tcl]\"
  source \"[file join [set dir] Progressbar.tcl]\"
  source \"[file join [set dir] Gridcontrol.tcl]\"
  source \"[file join [set dir] Listcontrol.tcl]\"
  source \"[file join [set dir] Iconbox.tcl]\"
  source \"[file join [set dir] Treecontrol.tcl]\"
  source \"[file join [set dir] Ibutton.tcl]\"
  source \"[file join [set dir] Spinentry.tcl]\"

  package provide mkWidgets 1.3
"
