# include "stdio.h"
#if defined(__cplusplus)
   extern "C" {
#endif
#if (defined(__cplusplus) || defined(__STDC__))
     extern int yyreject();
     extern int yywrap();
     extern int yylook();
     extern int yyback(int *, int);
     extern int yyinput();
     extern void yyoutput(int);
     extern void yyunput(int);
     extern int yylex();
     extern int yyless(int);
#ifdef LEXDEBUG
     extern void allprint();
     extern void sprint();
#endif
#if defined(__cplusplus)
   }
#endif
#endif	/* __cplusplus or __STDC__ */
# define U(x) x
# define NLSTATE yyprevious=YYNEWLINE
# define BEGIN yybgin = yysvec + 1 +
# define INITIAL 0
# define YYLERR yysvec
# define YYSTATE (yyestate-yysvec-1)
# define YYOPTIM 1
# define YYLMAX 200
# define output(c) putc(c,yyout)
# define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)
# define unput(c) {yytchar= (c);if(yytchar=='\n')yylineno--;*yysptr++=yytchar;}
# define yymore() (yymorfg=1)
# define ECHO fprintf(yyout, "%s",yytext)
# define REJECT { nstr = yyreject(); goto yyfussy;}
int yyleng;
int yylenguc;
extern unsigned char yytextarr[];
# ifdef YYCHAR_ARRAY
extern char yytext[];
# else
extern unsigned char yytext[];
# endif
int yyposix_point=0;
int yynls16=0;
int yynls_wchar=0;
char *yylocale = "C C C C C C";
int yymorfg;
extern unsigned char *yysptr, yysbuf[];
int yytchar;
FILE *yyin = {stdin}, *yyout = {stdout};
extern int yylineno;
struct yysvf { 
	int yystoff;
	struct yysvf *yyother;
	int *yystops;};
struct yysvf *yyestate;
extern struct yysvf yysvec[], *yybgin;
    1	      SUBROUTINE PACK_GP(KFILDO,IC,NXY,IS5,NS5,MINPK,INC,MISSP,MISSS,
    2	     1                   JMIN,JMAX,LBIT,NOV,NDG,LX,IBIT,JBIT,KBIT,
    3	     2                   NOVREF,LBITREF,IER,*)            
    4	C
    5	C        FEBRUARY 1994   GLAHN   TDL   MOS-2000
    6	C        JUNE     1995   GLAHN   MODIFIED FOR LMISS ERROR.
    7	C        JULY     1996   GLAHN   ADDED MISSS
    8	C        FEBRUARY 1997   GLAHN   REMOVED 4 REDUNDANT TESTS FOR
    9	C                                MISSP.EQ.0; INSERTED A TEST TO BETTER
   10	C                                HANDLE A STRING OF 9999'S
   11	C        FEBRUARY 1997   GLAHN   ADDED LOOPS TO ELIMINATE TEST FOR 
   12	C                                MISSS WHEN MISSS = 0
   13	C        MARCH    1997   GLAHN   CORRECTED FOR SECONDARY MISSING VALUE
   14	C        MARCH    1997   GLAHN   CORRECTED FOR USE OF LOCAL VALUE
   15	C                                OF MINPK
   16	C        MARCH    1997   GLAHN   CORRECTED FOR SECONDARY MISSING VALUE
   17	C        MARCH    1997   GLAHN   CHANGED CALCULATING NUMBER OF BITS 
   18	C                                THROUGH EXPONENTS TO AN ARRAY (IMPROVED
   19	C                                OVERALL PACKING PERFORMANCE BY ABOUT
   20	C                                35 PERCENT!).  ALLOWED 0 BITS FOR
   21	C                                PACKING JMIN( ), LBIT( ), AND NOV( ).
   22	C        MAY      1997   GLAHN   A NUMBER OF CHANGES FOR EFFICIENCY.
   23	C                                MOD FUNCTIONS ELIMINATED AND ONE
   24	C                                IFTHEN ADDED.  JOUNT REMOVED.
   25	C                                RECOMPUTATION OF BITS NOT MADE UNLESS
   26	C                                NECESSARY AFTER MOVING POINTS FROM
   27	C                                ONE GROUP TO ANOTHER.  NENDB ADJUSTED
   28	C                                TO ELIMINATE POSSIBILITY OF VERY
   29	C                                SMALL GROUP AT THE END. 
   30	C                                ABOUT 8 PERCENT IMPROVEMENT IN
   31	C                                OVERALL PACKING.  ISKIPA REMOVED;
   32	C                                THERE IS ALWAYS A GROUP B THAT CAN
   33	C                                BECOME GROUP A.  CONTROL ON SIZE 
   34	C                                OF GROUP B (STATEMENT BELOW 150)
   35	C                                ADDED.  ADDED ADDA, AND USE
   36	C                                OF GE AND LE INSTEAD OF GT AND LT
   37	C                                IN LOOPS BETWEEN 150 AND 160.
   38	C                                IBITBS ADDED TO SHORTEN TRIPS 
   39	C                                THROUGH LOOP.
   40	C        MARCH    2000   GLAHN   MODIFIED FOR GRIB2; CHANGED NAME FROM 
   41	C                                PACKGP
   42	C        JANUARY  2001   GLAHN   COMMENTS; IER = 706 SUBSTITUTED FOR
   43	C                                STOPS; ADDED RETURN1; REMOVED STATEMENT
   44	C                                NUMBER 110; ADDED IER AND * RETURN
   45	C        NOVEMBER 2001   GLAHN   CHANGED SOME DIAGNOSTIC FORMATS TO 
   46	C                                ALLOW PRINTING LARGER NUMBERS
   47	C        NOVEMBER 2001   GLAHN   ADDED MISSLX( ) TO PUT MAXIMUM VALUE
   48	C                                INTO JMIN( ) WHEN ALL VALUES MISSING
   49	C                                TO AGREE WITH GRIB STANDARD.
   50	C        NOVEMBER 2001   GLAHN   CHANGED TWO TESTS ON MISSP AND MISSS
   51	C                                EQ 0 TO TESTS ON IS5(23).  HOWEVER,
   52	C                                MISSP AND MISSS CANNOT IN GENERAL BE
   53	C                                = 0.
   54	C        NOVEMBER 2001   GLAHN   ADDED CALL TO REDUCE; DEFINED ITEST
   55	C                                BEFORE LOOPS TO REDUCE COMPUTATION;
   56	C                                STARTED LARGE GROUP WHEN ALL SAME
   57	C                                VALUE
   58	C        DECEMBER 2001   GLAHN   MODIFIED AND ADDED A FEW COMMENTS
   59	C        JANUARY  2002   GLAHN   REMOVED LOOP BEFORE 150 TO DETERMINE
   60	C                                A GROUP OF ALL SAME VALUE
   61	C        JANUARY  2002   GLAHN   CHANGED MALLOW FROM 9999999 TO 2**30+1,
   62	C                                AND MADE IT A PARAMETER
   63	C        MARCH    2002   GLAHN   ADDED NON FATAL IER = 716, 717;
   64	C                                REMOVED NENDB=NXY ABOVE 150; COMMENTS
   65	C
   66	C        PURPOSE
   67	C            DETERMINES GROUPS OF VARIABLE SIZE, BUT AT LEAST OF
   68	C            SIZE MINPK, THE ASSOCIATED MAX (JMAX( )) AND MIN (JMIN( )),
   69	C            THE NUMBER OF BITS NECESSARY TO HOLD THE VALUES IN EACH
   70	C            GROUP (LBIT( )), THE NUMBER OF VALUES IN EACH GROUP
   71	C            (NOV( )), THE NUMBER OF BITS NECESSARY TO PACK THE JMIN( )
   72	C            VALUES (IBIT), THE NUMBER OF BITS NECESSARY TO PACK THE
   73	C            LBIT( ) VALUES (JBIT), AND THE NUMBER OF BITS NECESSARY
   74	C            TO PACK THE NOV( ) VALUES (KBIT).  THE ROUTINE IS DESIGNED
   75	C            TO DETERMINE THE GROUPS SUCH THAT A SMALL NUMBER OF BITS
   76	C            IS NECESSARY TO PACK THE DATA WITHOUT EXCESSIVE
   77	C            COMPUTATIONS.  IF ALL VALUES IN THE GROUP ARE ZERO, THE
   78	C            NUMBER OF BITS TO USE IN PACKING IS DEFINED AS ZERO WHEN
   79	C            THERE CAN BE NO MISSING VALUES; WHEN THERE CAN BE MISSING
   80	C            VALUES, THE NUMBER OF BITS MUST BE AT LEAST 1 TO HAVE
   81	C            THE CAPABILITY TO RECOGNIZE THE MISSING VALUE.  HOWEVER,
   82	C            IF ALL VALUES IN A GROUP ARE MISSING, THE NUMBER OF BITS
   83	C            NEEDED IS 0, AND THE UNPACKER RECOGNIZES THIS.
   84	C            ALL VARIABLES ARE INTEGER.  EVEN THOUGH THE GROUPS ARE 
   85	C            INITIALLY OF SIZE MINPK OR LARGER, AN ADJUSTMENT BETWEEN
   86	C            TWO GROUPS (THE LOOKBACK PROCEDURE) MAY MAKE A GROUP 
   87	C            SMALLER THAN MINPK.  THE CONTROL ON GROUP SIZE IS THAT
   88	C            THE SUM OF THE SIZES OF THE TWO CONSECUTIVE GROUPS, EACH OF
   89	C            SIZE MINPK OR LARGER, IS NOT DECREASED.  WHEN DETERMINING
   90	C            THE NUMBER OF BITS NECESSARY FOR PACKING, THE LARGEST
   91	C            VALUE THAT CAN BE ACCOMMODATED IN, SAY, MBITS, IS
   92	C            2**MBITS-1; THIS LARGEST VALUE (AND THE NEXT SMALLEST
   93	C            VALUE) IS RESERVED FOR THE MISSING VALUE INDICATOR (ONLY)
   94	C            WHEN IS5(23) NE 0.  IF THE DIMENSION NDG
   95	C            IS NOT LARGE ENOUGH TO HOLD ALL THE GROUPS, THE LOCAL VALUE
   96	C            OF MINPK IS INCREASED BY 50 PERCENT.  THIS IS REPEATED
   97	C            UNTIL NDG WILL SUFFICE.  A DIAGNOSTIC IS PRINTED WHENEVER
   98	C            THIS HAPPENS, WHICH SHOULD BE VERY RARELY.  IF IT HAPPENS
   99	C            OFTEN, NDG IN SUBROUTINE PACK SHOULD BE INCREASED AND
  100	C            A CORRESPONDING INCREASE IN SUBROUTINE UNPACK MADE. 
  101	C            CONSIDERABLE CODE IS PROVIDED SO THAT NO MORE CHECKING
  102	C            FOR MISSING VALUES WITHIN LOOPS IS DONE THAN NECESSARY;
  103	C            THE ADDED EFFICIENCY OF THIS IS RELATIVELY MINOR,
  104	C            BUT DOES NO HARM.  FOR GRIB2, THE REFERENCE VALUE FOR
  105	C            THE LENGTH OF GROUPS IN NOV( ) AND FOR THE NUMBER OF
  106	C            BITS NECESSARY TO PACK GROUP VALUES ARE DETERMINED,
  107	C            AND SUBTRACTED BEFORE JBIT AND KBIT ARE DETERMINED.
  108	C
  109	C            WHEN 1 OR MORE GROUPS ARE LARGE COMPARED TO THE OTHERS,
  110	C            THE WIDTH OF ALL GROUPS MUST BE AS LARGE AS THE LARGEST.
  111	C            A SUBROUTINE REDUCE BREAKS UP LARGE GROUPS INTO 2 OR
  112	C            MORE TO REDUCE TOTAL BITS REQUIRED.  IF REDUCE SHOULD
  113	C            ABORT, PACK_GP WILL BE EXECUTED AGAIN WITHOUT THE CALL
  114	C            TO REDUCE.
  115	C
  116	C        DATA SET USE 
  117	C           KFILDO - UNIT NUMBER FOR OUTPUT (PRINT) FILE. (OUTPUT) 
  118	C
  119	C        VARIABLES IN CALL SEQUENCE 
  120	C              KFILDO = UNIT NUMBER FOR OUTPUT (PRINT) FILE.  (INPUT)
  121	C               IC( ) = ARRAY TO HOLD DATA FOR PACKING.  THE VALUES
  122	C                       DO NOT HAVE TO BE POSITIVE AT THIS POINT, BUT
  123	C                       MUST BE IN THE RANGE -2**30 TO +2**30 (THE 
  124	C                       THE VALUE OF MALLOW).  THESE INTEGER VALUES
  125	C                       WILL BE RETAINED EXACTLY THROUGH PACKING AND
  126	C                       UNPACKING.  (INPUT)
  127	C                 NXY = NUMBER OF VALUES IN IC( ).  ALSO TREATED
  128	C                       AS ITS DIMENSION.  (INPUT)
  129	C              IS5(K) = CONTAINS DATA THAT CORRESPONDS TO SECTION
  130	C                       5 OF THE GRIB2 MESSAGE (K=1,NS5).
  131	C                       (INPUT)
  132	C                 NS5 = DIMENSION OF IS5( ). (INPUT)
  133	C               MINPK = THE MINIMUM SIZE OF EACH GROUP, EXCEPT POSSIBLY
  134	C                       THE LAST ONE.  (INPUT)
  135	C                 INC = THE NUMBER OF VALUES TO ADD TO AN ALREADY
  136	C                       EXISTING GROUP IN DETERMINING WHETHER OR NOT
  137	C                       TO START A NEW GROUP.  IDEALLY, THIS WOULD BE
  138	C                       1, BUT EACH TIME INC VALUES ARE ATTEMPTED, THE
  139	C                       MAX AND MIN OF THE NEXT MINPK VALUES MUST BE
  140	C                       FOUND.  THIS IS "A LOOP WITHIN A LOOP," AND
  141	C                       A SLIGHTLY LARGER VALUE MAY GIVE ABOUT AS GOOD
  142	C                       RESULTS WITH SLIGHTLY LESS COMPUTATIONAL TIME.
  143	C                       IF INC IS LE 0, 1 IS USED, AND A DIAGNOSTIC IS
  144	C                       OUTPUT.  NOTE:  IT IS EXPECTED THAT INC WILL
  145	C                       EQUAL 1.  THE CODE USES INC PRIMARILY IN THE
  146	C                       LOOPS STARTING AT STATEMENT 180.  IF INC
  147	C                       WERE 1, THERE WOULD NOT NEED TO BE LOOPS
  148	C                       AS SUCH.  HOWEVER, KINC (THE LOCAL VALUE OF
  149	C                       INC) IS SET GE 1 WHEN NEAR THE END OF THE DATA
  150	C                       TO FORESTALL A VERY SMALL GROUP AT THE END. 
  151	C                       (INPUT)
  152	C               MISSP = WHEN MISSING POINTS CAN BE PRESENT IN THE DATA,
  153	C                       THEY WILL HAVE THE VALUE MISSP OR MISSS.
  154	C                       MISSP IS THE PRIMARY MISSING VALUE AND  MISSS
  155	C                       IS THE SECONDARY MISSING VALUE .  THESE MUST
  156	C                       NOT BE VALUES THAT WOULD OCCUR WITH SUBTRACTING
  157	C                       THE MINIMUM (REFERENCE) VALUE OR SCALING.
  158	C                       FOR EXAMPLE, MISSP = 0 WOULD NOT BE ADVISABLE.
  159	C                       (INPUT)
  160	C               MISSS = SECONDARY MISSING VALUE INDICATOR (SEE MISSP).
  161	C                       (INPUT)
  162	C             JMIN(J) = THE MINIMUM OF EACH GROUP (J=1,LX).  (OUTPUT)
  163	C             JMAX(J) = THE MAXIMUM OF EACH GROUP (J=1,LX).  THIS IS
  164	C                       NOT REALLY NEEDED, BUT SINCE THE MAX OF EACH
  165	C                       GROUP MUST BE FOUND, SAVING IT HERE IS CHEAP
  166	C                       IN CASE THE USER WANTS IT.  (OUTPUT)
  167	C             LBIT(J) = THE NUMBER OF BITS NECESSARY TO PACK EACH GROUP
  168	C                       (J=1,LX).  IT IS ASSUMED THE MINIMUM OF EACH
  169	C                       GROUP WILL BE REMOVED BEFORE PACKING, AND THE
  170	C                       VALUES TO PACK WILL, THEREFORE, ALL BE POSITIVE.
  171	C                       HOWEVER, IC( ) DOES NOT NECESSARILY CONTAIN
  172	C                       ALL POSITIVE VALUES.  IF THE OVERALL MINIMUM
  173	C                       HAS BEEN REMOVED (THE USUAL CASE), THEN IC( )
  174	C                       WILL CONTAIN ONLY POSITIVE VALUES.  (OUTPUT)
  175	C              NOV(J) = THE NUMBER OF VALUES IN EACH GROUP (J=1,LX).
  176	C                       (OUTPUT)
  177	C                 NDG = THE DIMENSION OF JMIN( ), JMAX( ), LBIT( ), AND
  178	C                       NOV( ).  (INPUT)
  179	C                  LX = THE NUMBER OF GROUPS DETERMINED.  (OUTPUT)
  180	C                IBIT = THE NUMBER OF BITS NECESSARY TO PACK THE JMIN(J)
  181	C                       VALUES, J=1,LX.  (OUTPUT)
  182	C                JBIT = THE NUMBER OF BITS NECESSARY TO PACK THE LBIT(J)
  183	C                       VALUES, J=1,LX.  (OUTPUT)
  184	C                KBIT = THE NUMBER OF BITS NECESSARY TO PACK THE NOV(J)
  185	C                       VALUES, J=1,LX.  (OUTPUT)
  186	C              NOVREF = REFERENCE VALUE FOR NOV( ).  (OUTPUT)
  187	C             LBITREF = REFERENCE VALUE FOR LBIT( ).  (OUTPUT)
  188	C                 IER = ERROR RETURN.
  189	C                       706 = VALUE WILL NOT PACK IN 30 BITS.
  190	C                       (OUTPUT)
  191	C                   * = ALTERNATE RETURN WHEN IER NE 0.
  192	C
  193	C        INTERNAL VARIABLES 
  194	C               CFEED = CONTAINS THE CHARACTER REPRESENTATION
  195	C                       OF A PRINTER FORM FEED.
  196	C               IFEED = CONTAINS THE INTEGER VALUE OF A PRINTER
  197	C                       FORM FEED.
  198	C                KINC = WORKING COPY OF INC.  MAY BE MODIFIED.
  199	C                MINA = MINIMUM VALUE IN GROUP A.
  200	C                MAXA = MAXIMUM VALUE IN GROUP A.
  201	C               NENDA = THE PLACE IN IC( ) WHERE GROUP A ENDS.
  202	C              KSTART = THE PLACE IN IC( ) WHERE GROUP A STARTS.
  203	C               IBITA = NUMBER OF BITS NEEDED TO HOLD VALUES IN GROUP A.
  204	C                MINB = MINIMUM VALUE IN GROUP B.
  205	C                MAXB = MAXIMUM VALUE IN GROUP B.
  206	C               NENDB = THE PLACE IN IC( ) WHERE GROUP B ENDS.
  207	C               IBITB = NUMBER OF BITS NEEDED TO HOLD VALUES IN GROUP B.
  208	C                MINC = MINIMUM VALUE IN GROUP C.
  209	C                MAXC = MAXIMUM VALUE IN GROUP C.
  210	C              KTOTAL = COUNT OF NUMBER OF VALUES IN IC( ) PROCESSED.
  211	C               NOUNT = NUMBER OF VALUES ADDED TO GROUP A.
  212	C               LMISS = 0 WHEN IS5(23) = 0.  WHEN PACKING INTO A 
  213	C                       SPECIFIC NUMBER OF BITS, SAY MBITS,
  214	C                       THE MAXIMUM VALUE THAT CAN BE HANDLED IS
  215	C                       2**MBITS-1.  WHEN IS5(23) = 1, INDICATING
  216	C                       PRIMARY MISSING VALUES, THIS MAXIMUM VALUE 
  217	C                       IS RESERVED TO HOLD THE PRIMARY MISSING VALUE 
  218	C                       INDICATOR AND LMISS = 1.  WHEN IS5(23) = 2,
  219	C                       THE VALUE JUST BELOW THE MAXIMUM (I.E.,
  220	C                       2**MBITS-2) IS RESERVED TO HOLD THE SECONDARY 
  221	C                       MISSING VALUE INDICATOR AND LMISS = 2.
  222	C              LMINPK = LOCAL VALUE OF MINPK.  THIS WILL BE ADJUSTED
  223	C                       UPWARD WHENEVER NDG IS NOT LARGE ENOUGH TO HOLD
  224	C                       ALL THE GROUPS.
  225	C              MALLOW = THE LARGEST ALLOWABLE VALUE FOR PACKING.
  226	C              MISLLA = SET TO 1 WHEN ALL VALUES IN GROUP A ARE MISSING.
  227	C                       THIS IS USED TO DISTINGUISH BETWEEN A REAL
  228	C                       MINIMUM WHEN ALL VALUES ARE NOT MISSING
  229	C                       AND A MINIMUM THAT HAS BEEN SET TO ZERO WHEN
  230	C                       ALL VALUES ARE MISSING.  0 OTHERWISE.
  231	C                       NOTE THAT THIS DOES NOT DISTINGUISH BETWEEN
  232	C                       PRIMARY AND SECONDARY MISSINGS WHEN SECONDARY
  233	C                       MISSINGS ARE PRESENT.  THIS MEANS THAT 
  234	C                       LBIT( ) WILL NOT BE ZERO WITH THE RESULTING
  235	C                       COMPRESSION EFFICIENCY WHEN SECONDARY MISSINGS
  236	C                       ARE PRESENT.  ALSO NOTE THAT A CHECK HAS BEEN
  237	C                       MADE EARLIER TO DETERMINE THAT SECONDARY
  238	C                       MISSINGS ARE REALLY THERE.
  239	C              MISLLB = SET TO 1 WHEN ALL VALUES IN GROUP B ARE MISSING.
  240	C                       THIS IS USED TO DISTINGUISH BETWEEN A REAL
  241	C                       MINIMUM WHEN ALL VALUES ARE NOT MISSING
  242	C                       AND A MINIMUM THAT HAS BEEN SET TO ZERO WHEN
  243	C                       ALL VALUES ARE MISSING.  0 OTHERWISE.
  244	C              MISLLC = PERFORMS THE SAME FUNCTION FOR GROUP C THAT
  245	C                       MISLLA AND MISLLB DO FOR GROUPS B AND C,
  246	C                       RESPECTIVELY.
  247	C            IBXX2(J) = AN ARRAY THAT WHEN THIS ROUTINE IS FIRST ENTERED
  248	C                       IS SET TO 2**J, J=0,30. IBXX2(30) = 2**30, WHICH
  249	C                       IS THE LARGEST VALUE PACKABLE, BECAUSE 2**31
  250	C                       IS LARGER THAN THE INTEGER WORD SIZE.
  251	C              IFIRST = SET BY DATA STATEMENT TO 0.  CHANGED TO 1 ON
  252	C                       FIRST
  253	C                       ENTRY WHEN IBXX2( ) IS FILLED.
  254	C               MINAK = KEEPS TRACK OF THE LOCATION IN IC( ) WHERE THE 
  255	C                       MINIMUM VALUE IN GROUP A IS LOCATED.
  256	C               MAXAK = DOES THE SAME AS MINAK, EXCEPT FOR THE MAXIMUM.
  257	C               MINBK = THE SAME AS MINAK FOR GROUP B.
  258	C               MAXBK = THE SAME AS MAXAK FOR GROUP B.
  259	C               MINCK = THE SAME AS MINAK FOR GROUP C.
  260	C               MAXCK = THE SAME AS MAXAK FOR GROUP C.
  261	C                ADDA = KEEPS TRACK WHETHER OR NOT AN ATTEMPT TO ADD
  262	C                       POINTS TO GROUP A WAS MADE.  IF SO, THEN ADDA
  263	C                       KEEPS FROM TRYING TO PUT ONE BACK INTO B.
  264	C                       (LOGICAL)
  265	C              IBITBS = KEEPS CURRENT VALUE IF IBITB SO THAT LOOP
  266	C                       ENDING AT 166 DOESN'T HAVE TO START AT
  267	C                       IBITB = 0 EVERY TIME.
  268	C           MISSLX(J) = MALLOW EXCEPT WHEN A GROUP IS ALL ONE VALUE (AND
  269	C                       LBIT(J) = 0) AND THAT VALUE IS MISSING.  IN
  270	C                       THAT CASE, MISSLX(J) IS MISSP OR MISSS.  THIS
  271	C                       GETS INSERTED INTO JMIN(J) LATER AS THE 
  272	C                       MISSING INDICATOR; IT CAN'T BE PUT IN UNTIL
  273	C                       THE END, BECAUSE JMIN( ) IS USED TO CALCULATE
  274	C                       THE MAXIMUM NUMBER OF BITS (IBITS) NEEDED TO
  275	C                       PACK JMIN( ).
  276	C        1         2         3         4         5         6         7 X
  277	C
  278	C        NON SYSTEM SUBROUTINES CALLED 
  279	C           NONE
  280	C
  281	      PARAMETER (MALLOW=2**30+1)
  282	C
  283	      CHARACTER*1 CFEED
  284	      LOGICAL ADDA
  285	C
  286	      DIMENSION IC(NXY),IS5(NS5)
  287	      DIMENSION JMIN(NDG),JMAX(NDG),LBIT(NDG),NOV(NDG)
  288	      DIMENSION MISSLX(NDG)
  289	C        MISSLX( ) IS AN AUTOMATIC ARRAY.
  290	      DIMENSION IBXX2(0:30)
  291	C
  292	      SAVE IBXX2
  293	C
  294	      DATA IFEED/12/
  295	      DATA IFIRST/0/
  296	C
  297	      IER=0
  298	D     CALL TIMPR(KFILDO,KFILDO,'START PACK_GP        ')
  299	      CFEED=CHAR(IFEED)
  300	C
  301	      IRED=0
  302	C        IRED IS A FLAG.  WHEN ZERO, REDUCE WILL BE CALLED.
  303	C        IF REDUCE ABORTS, IRED = 1 AND IS NOT CALLED.  IN
  304	C        THIS CASE PACK_GP EXECUTES AGAIN EXCEPT FOR REDUCE.
  305	C
  306	      IF(INC.LE.0)THEN
  307	         IERSAV=717
  308	D        WRITE(KFILDO,101)INC
  309	D101     FORMAT(/' ****INC ='I8,' NOT CORRECT IN PACK_GP.  1 IS USED.')
  310	      ENDIF
  311	C
  312	C        THERE WILL BE A RESTART OF PACK_GP IF SUBROUTINE REDUCE
  313	C        ABORTS.  THIS SHOULD NOT HAPPEN, BUT IF IT DOES, PACK_GP
  314	C        WILL COMPLETE WITHOUT SUBROUTINE REDUCE.  A NON FATAL
  315	C        DIAGNOSTIC RETURN IS PROVIDED.
  316	C
  317	 102  KINC=MAX(INC,1)
  318	      LMINPK=MINPK
  319	C
  320	C         CALCULATE THE POWERS OF 2 THE FIRST TIME ENTERED.
  321	C
  322	      IF(IFIRST.EQ.0)THEN
  323	         IFIRST=1
  324	         IBXX2(0)=1
  325	C
  326	         DO 104 J=1,30
  327	         IBXX2(J)=IBXX2(J-1)*2
  328	 104     CONTINUE
  329	C
  330	      ENDIF
  331	C
  332	C        THERE WILL BE A RESTART AT 105 IS NDG IS NOT LARGE ENOUGH.
  333	C        A NON FATAL DIAGNOSTIC RETURN IS PROVIDED.
  334	C
  335	 105  KSTART=1
  336	      KTOTAL=0
  337	      LX=0
  338	      ADDA=.FALSE.
  339	      LMISS=0
  340	      IF(IS5(23).EQ.1)LMISS=1
  341	      IF(IS5(23).EQ.2)LMISS=2
  342	C
  343	C        *************************************
  344	C
  345	C        THIS SECTION COMPUTES STATISTICS FOR GROUP A.  GROUP A IS
  346	C        A GROUP OF SIZE LMINPK.
  347	C
  348	C        *************************************
  349	C
  350	      IBITA=0
  351	      MINA=MALLOW
  352	      MAXA=-MALLOW
  353	      MINAK=MALLOW
  354	      MAXAK=-MALLOW
  355	C
  356	C        FIND THE MIN AND MAX OF GROUP A.  THIS WILL INITIALLY BE OF
  357	C        SIZE LMINPK (IF THERE ARE STILL LMINPK VALUES IN IC( )), BUT
  358	C        WILL INCREASE IN SIZE IN INCREMENTS OF INC UNTIL A NEW
  359	C        GROUP IS STARTED.  THE DEFINITION OF GROUP A IS DONE HERE
  360	C        ONLY ONCE (UPON INITIAL ENTRY), BECAUSE A GROUP B CAN ALWAYS
  361	C        BECOME A NEW GROUP A AFTER A IS PACKED, EXCEPT IF LMINPK 
  362	C        HAS TO BE INCREASED BECAUSE NDG IS TOO SMALL.  THEREFORE,
  363	C        THE SEPARATE LOOPS FOR MISSING AND NON-MISSING HERE BUYS
  364	C        ALMOST NOTHING.
  365	C
  366	      NENDA=MIN(KSTART+LMINPK-1,NXY)
  367	      IF(NXY-NENDA.LE.LMINPK/2)NENDA=NXY
  368	C        ABOVE STATEMENT GUARANTEES THE LAST GROUP IS GT LMINPK/2 BY 
  369	C        MAKING THE ACTUAL GROUP LARGER.  IF A PROVISION LIKE THIS IS 
  370	C        NOT INCLUDED, THERE WILL MANY TIMES BE A VERY SMALL GROUP
  371	C        AT THE END.  USE SEPARATE LOOPS FOR MISSING AND NO MISSING
  372	C        VALUES FOR EFFICIENCY.
  373	C
  374	C        DETERMINE WHETHER THERE IS A LONG STRING OF THE SAME VALUE
  375	C        UNLESS NENDA = NXY.  THIS MAY ALLOW A LARGE GROUP A TO
  376	C        START WITH, AS WITH MISSING VALUES.   SEPARATE LOOPS FOR
  377	C        MISSING OPTIONS.  THIS SECTION IS ONLY EXECUTED ONCE,
  378	C        IN DETERMINING THE FIRST GROUP.  IT HELPS FOR AN ARRAY
  379	C        OF MOSTLY MISSING VALUES OR OF ONE VALUE, SUCH AS
  380	C        RADAR OR PRECIP DATA.
  381	C
  382	      IF(NENDA.NE.NXY.AND.IC(KSTART).EQ.IC(KSTART+1))THEN
  383	C           NO NEED TO EXECUTE IF FIRST TWO VALUES ARE NOT EQUAL.
  384	C
  385	         IF(IS5(23).EQ.0)THEN
  386	C              THIS LOOP IS FOR NO MISSING VALUES.
  387	C
  388	            DO 111 K=KSTART+1,NXY
  389	C
  390	               IF(IC(K).NE.IC(KSTART))THEN
  391	                  NENDA=MAX(NENDA,K-1)
  392	                  GO TO 114
  393	               ENDIF
  394	C
  395	 111        CONTINUE
  396	C
  397	            NENDA=NXY
  398	C              FALL THROUGH THE LOOP MEANS ALL VALUES ARE THE SAME.
  399	C
  400	         ELSEIF(IS5(23).EQ.1)THEN
  401	C              THIS LOOP IS FOR PRIMARY MISSING VALUES ONLY.
  402	C
  403	            DO 112 K=KSTART+1,NXY
  404	C        
  405	               IF(IC(K).NE.MISSP)THEN
  406	C
  407	                  IF(IC(K).NE.IC(KSTART))THEN
  408	                     NENDA=MAX(NENDA,K-1)
  409	                     GO TO 114
  410	                  ENDIF
  411	C
  412	               ENDIF
  413	C
  414	 112        CONTINUE
  415	C
  416	            NENDA=NXY
  417	C              FALL THROUGH THE LOOP MEANS ALL VALUES ARE THE SAME.
  418	C
  419	         ELSE
  420	C              THIS LOOP IS FOR PRIMARY AND SECONDARY MISSING VALUES.
  421	C
  422	            DO 113 K=KSTART+1,NXY
  423	C        
  424	               IF(IC(K).NE.MISSP.AND.IC(K).NE.MISSS)THEN
  425	C
  426	                  IF(IC(K).NE.IC(KSTART))THEN
  427	                     NENDA=MAX(NENDA,K-1)
  428	                     GO TO 114
  429	                  ENDIF
  430	C
  431	               ENDIF
  432	C
  433	 113        CONTINUE
  434	C
  435	            NENDA=NXY
  436	C              FALL THROUGH THE LOOP MEANS ALL VALUES ARE THE SAME.
  437	         ENDIF
  438	C
  439	      ENDIF
  440	C
  441	 114  IF(IS5(23).EQ.0)THEN
  442	C
  443	         DO 115 K=KSTART,NENDA
  444	         IF(IC(K).LT.MINA)THEN
  445	            MINA=IC(K)
  446	            MINAK=K
  447	         ENDIF
  448	         IF(IC(K).GT.MAXA)THEN
  449	            MAXA=IC(K)
  450	            MAXAK=K
  451	         ENDIF
  452	 115     CONTINUE
  453	C
  454	      ELSEIF(IS5(23).EQ.1)THEN
  455	C
  456	         DO 117 K=KSTART,NENDA
  457	         IF(IC(K).EQ.MISSP)GO TO 117
  458	         IF(IC(K).LT.MINA)THEN
  459	            MINA=IC(K)
  460	            MINAK=K
  461	         ENDIF
  462	         IF(IC(K).GT.MAXA)THEN
  463	            MAXA=IC(K)
  464	            MAXAK=K
  465	         ENDIF
  466	 117     CONTINUE
  467	C
  468	      ELSE
  469	C
  470	         DO 120 K=KSTART,NENDA
  471	         IF(IC(K).EQ.MISSP.OR.IC(K).EQ.MISSS)GO TO 120
  472	         IF(IC(K).LT.MINA)THEN
  473	            MINA=IC(K)
  474	            MINAK=K
  475	         ENDIF
  476	         IF(IC(K).GT.MAXA)THEN
  477	            MAXA=IC(K)
  478	            MAXAK=K
  479	         ENDIF
  480	 120     CONTINUE
  481	C
  482	      ENDIF
  483	C
  484	      KOUNTA=NENDA-KSTART+1
  485	C
  486	C        INCREMENT KTOTAL AND FIND THE BITS NEEDED TO PACK THE A GROUP.
  487	C
  488	      KTOTAL=KTOTAL+KOUNTA
  489	      MISLLA=0
  490	      IF(MINA.NE.MALLOW)GO TO 125
  491	C        ALL MISSING VALUES MUST BE ACCOMMODATED.
  492	      MINA=0
  493	      MAXA=0
  494	      MISLLA=1
  495	      IBITB=0
  496	      IF(IS5(23).NE.2)GO TO 130
  497	C        WHEN ALL VALUES ARE MISSING AND THERE ARE NO
  498	C        SECONDARY MISSING VALUES, IBITA = 0.
  499	C        OTHERWISE, IBITA MUST BE CALCULATED.
  500	C
  501	 125  ITEST=MAXA-MINA+LMISS
  502	C  
  503	      DO 126 IBITA=0,30
  504	      IF(ITEST.LT.IBXX2(IBITA))GO TO 130
  505	C***        THIS TEST IS THE SAME AS:
  506	C***     IF(MAXA-MINA.LT.IBXX2(IBITA)-LMISS)GO TO 130
  507	 126  CONTINUE
  508	C
  509	D     WRITE(KFILDO,127)MAXA,MINA
  510	D127  FORMAT(' ****ERROR IN PACK_GP.  VALUE WILL NOT PACK IN 30 BITS.',
  511	D    1       '  MAXA ='I13,'  MINA ='I13,'.  ERROR AT 127.')
  512	      IER=706
  513	      GO TO 900
  514	C
  515	 130  CONTINUE
  516	C
  517	C***D     WRITE(KFILDO,131)KOUNTA,KTOTAL,MINA,MAXA,IBITA,MISLLA
  518	C***D131  FORMAT(' AT 130, KOUNTA ='I8,'  KTOTAL ='I8,'  MINA ='I8,
  519	C***D    1       '  MAXA ='I8,'  IBITA ='I3,'  MISLLA ='I3) 
  520	C
  521	 133  IF(KTOTAL.GE.NXY)GO TO 200
  522	C
  523	C        *************************************
  524	C
  525	C        THIS SECTION COMPUTES STATISTICS FOR GROUP B.  GROUP B IS A
  526	C        GROUP OF SIZE LMINPK IMMEDIATELY FOLLOWING GROUP A.
  527	C
  528	C        *************************************
  529	C
  530	 140  MINB=MALLOW
  531	      MAXB=-MALLOW
  532	      MINBK=MALLOW
  533	      MAXBK=-MALLOW
  534	      IBITBS=0
  535	      MSTART=KTOTAL+1
  536	C
  537	C        DETERMINE WHETHER THERE IS A LONG STRING OF THE SAME VALUE.
  538	C        THIS WORKS WHEN THERE ARE NO MISSING VALUES.
  539	C
  540	      NENDB=1
  541	C
  542	      IF(MSTART.LT.NXY)THEN
  543	C
  544	         IF(IS5(23).EQ.0)THEN
  545	C              THIS LOOP IS FOR NO MISSING VALUES.
  546	C
  547	            DO 145 K=MSTART+1,NXY
  548	C
  549	               IF(IC(K).NE.IC(MSTART))THEN
  550	                  NENDB=K-1
  551	                  GO TO 150
  552	               ENDIF
  553	C
  554	 145        CONTINUE
  555	C
  556	            NENDB=NXY
  557	C              FALL THROUGH THE LOOP MEANS ALL REMAINING VALUES
  558	C              ARE THE SAME.
  559	         ENDIF
  560	C
  561	      ENDIF
  562	C         
  563	 150  NENDB=MAX(NENDB,MIN(KTOTAL+LMINPK,NXY))
  564	C**** 150  NENDB=MIN(KTOTAL+LMINPK,NXY)
  565	C
  566	      IF(NXY-NENDB.LE.LMINPK/2)NENDB=NXY
  567	C        ABOVE STATEMENT GUARANTEES THE LAST GROUP IS GT LMINPK/2 BY 
  568	C        MAKING THE ACTUAL GROUP LARGER.  IF A PROVISION LIKE THIS IS 
  569	C        NOT INCLUDED, THERE WILL MANY TIMES BE A VERY SMALL GROUP
  570	C        AT THE END.  USE SEPARATE LOOPS FOR MISSING AND NO MISSING
  571	C
  572	C        USE SEPARATE LOOPS FOR MISSING AND NO MISSING VALUES
  573	C        FOR EFFICIENCY.
  574	C
  575	      IF(IS5(23).EQ.0)THEN
  576	C              
  577	         DO 155 K=MSTART,NENDB
  578	         IF(IC(K).LE.MINB)THEN
  579	            MINB=IC(K)
  580	C              NOTE LE, NOT LT.  LT COULD BE USED BUT THEN A 
  581	C              RECOMPUTE OVER THE WHOLE GROUP WOULD BE NEEDED
  582	C              MORE OFTEN.  SAME REASONING FOR GE AND OTHER
  583	C              LOOPS BELOW.
  584	            MINBK=K
  585	         ENDIF
  586	         IF(IC(K).GE.MAXB)THEN
  587	            MAXB=IC(K)
  588	            MAXBK=K
  589	         ENDIF
  590	 155     CONTINUE
  591	C
  592	      ELSEIF(IS5(23).EQ.1)THEN
  593	C
  594	         DO 157 K=MSTART,NENDB
  595	         IF(IC(K).EQ.MISSP)GO TO 157
  596	         IF(IC(K).LE.MINB)THEN
  597	            MINB=IC(K)
  598	            MINBK=K
  599	         ENDIF
  600	         IF(IC(K).GE.MAXB)THEN
  601	            MAXB=IC(K)
  602	            MAXBK=K
  603	         ENDIF
  604	 157     CONTINUE
  605	C
  606	      ELSE
  607	C
  608	         DO 160 K=MSTART,NENDB
  609	         IF(IC(K).EQ.MISSP.OR.IC(K).EQ.MISSS)GO TO 160
  610	         IF(IC(K).LE.MINB)THEN
  611	            MINB=IC(K)
  612	            MINBK=K
  613	         ENDIF
  614	         IF(IC(K).GE.MAXB)THEN
  615	            MAXB=IC(K)
  616	            MAXBK=K
  617	         ENDIF
  618	 160     CONTINUE
  619	C
  620	      ENDIF
  621	C
  622	      KOUNTB=NENDB-KTOTAL
  623	      MISLLB=0
  624	      IF(MINB.NE.MALLOW)GO TO 165
  625	C        ALL MISSING VALUES MUST BE ACCOMMODATED.
  626	      MINB=0
  627	      MAXB=0
  628	      MISLLB=1
  629	      IBITB=0
  630	C
  631	      IF(IS5(23).NE.2)GO TO 170
  632	C        WHEN ALL VALUES ARE MISSING AND THERE ARE NO SECONDARY
  633	C        MISSING VALUES, IBITB = 0.  OTHERWISE, IBITB MUST BE
  634	C        CALCULATED.
  635	C
  636	 165  DO 166 IBITB=IBITBS,30
  637	         IF(MAXB-MINB.LT.IBXX2(IBITB)-LMISS)GO TO 170
  638	 166  CONTINUE
  639	C
  640	D     WRITE(KFILDO,167)MAXB,MINB
  641	D167  FORMAT(' ****ERROR IN PACK_GP.  VALUE WILL NOT PACK IN 30 BITS.',
  642	D    1       '  MAXB ='I13,'  MINB ='I13,'.  ERROR AT 167.')
  643	      IER=706
  644	      GO TO 900
  645	C
  646	C        COMPARE THE BITS NEEDED TO PACK GROUP B WITH THOSE NEEDED
  647	C        TO PACK GROUP A.  IF IBITB GE IBITA, TRY TO ADD TO GROUP A.
  648	C        IF NOT, TRY TO ADD A'S POINTS TO B, UNLESS ADDITION TO A
  649	C        HAS BEEN DONE.  THIS LATTER IS CONTROLLED WITH ADDA.
  650	C
  651	 170  CONTINUE
  652	C
  653	C***D     WRITE(KFILDO,171)KOUNTA,KTOTAL,MINA,MAXA,IBITA,MISLLA,
  654	C***D    1                               MINB,MAXB,IBITB,MISLLB
  655	C***D171  FORMAT(' AT 171, KOUNTA ='I8,'  KTOTAL ='I8,'  MINA ='I8,
  656	C***D    1       '  MAXA ='I8,'  IBITA ='I3,'  MISLLA ='I3,
  657	C***D    2       '  MINB ='I8,'  MAXB ='I8,'  IBITB ='I3,'  MISLLB ='I3)  
  658	C
  659	      IF(IBITB.GE.IBITA)GO TO 180
  660	      IF(ADDA)GO TO 200
  661	C
  662	C        *************************************
  663	C
  664	C        GROUP B REQUIRES LESS BITS THAN GROUP A.  PUT AS MANY OF A'S
  665	C        POINTS INTO B AS POSSIBLE WITHOUT EXCEEDING THE NUMBER OF
  666	C        BITS NECESSARY TO PACK GROUP B.
  667	C
  668	C        *************************************
  669	C
  670	      KOUNTS=KOUNTA
  671	C        KOUNTA REFERS TO THE PRESENT GROUP A.
  672	      MINTST=MINB
  673	      MAXTST=MAXB
  674	      MINTSTK=MINBK
  675	      MAXTSTK=MAXBK
  676	C
  677	C        USE SEPARATE LOOPS FOR MISSING AND NO MISSING VALUES
  678	C        FOR EFFICIENCY.
  679	C
  680	      IF(IS5(23).EQ.0)THEN
  681	C 
  682	         DO 1715 K=KTOTAL,KSTART,-1
  683	C           START WITH THE END OF THE GROUP AND WORK BACKWARDS.
  684	         IF(IC(K).LT.MINB)THEN
  685	            MINTST=IC(K)
  686	            MINTSTK=K
  687	         ELSEIF(IC(K).GT.MAXB)THEN
  688	            MAXTST=IC(K)
  689	            MAXTSTK=K
  690	         ENDIF
  691	         IF(MAXTST-MINTST.GE.IBXX2(IBITB))GO TO 174
  692	C           NOTE THAT FOR THIS LOOP, LMISS = 0.
  693	         MINB=MINTST
  694	         MAXB=MAXTST
  695	         MINBK=MINTSTK
  696	         MAXBK=MAXTSTK
  697	         KOUNTA=KOUNTA-1
  698	C           THERE IS ONE LESS POINT NOW IN A.
  699	 1715    CONTINUE  
  700	C
  701	      ELSEIF(IS5(23).EQ.1)THEN            
  702	C
  703	         DO 1719 K=KTOTAL,KSTART,-1
  704	C           START WITH THE END OF THE GROUP AND WORK BACKWARDS.
  705	         IF(IC(K).EQ.MISSP)GO TO 1718
  706	         IF(IC(K).LT.MINB)THEN
  707	            MINTST=IC(K)
  708	            MINTSTK=K
  709	         ELSEIF(IC(K).GT.MAXB)THEN
  710	            MAXTST=IC(K)
  711	            MAXTSTK=K
  712	         ENDIF
  713	         IF(MAXTST-MINTST.GE.IBXX2(IBITB)-LMISS)GO TO 174
  714	C           FOR THIS LOOP, LMISS = 1.
  715	         MINB=MINTST
  716	         MAXB=MAXTST
  717	         MINBK=MINTSTK
  718	         MAXBK=MAXTSTK
  719	         MISLLB=0
  720	C           WHEN THE POINT IS NON MISSING, MISLLB SET = 0.
  721	 1718    KOUNTA=KOUNTA-1
  722	C           THERE IS ONE LESS POINT NOW IN A.
  723	 1719    CONTINUE  
  724	C
  725	      ELSE             
  726	C
  727	         DO 173 K=KTOTAL,KSTART,-1
  728	C           START WITH THE END OF THE GROUP AND WORK BACKWARDS.
  729	         IF(IC(K).EQ.MISSP.OR.IC(K).EQ.MISSS)GO TO 1729
  730	         IF(IC(K).LT.MINB)THEN
  731	            MINTST=IC(K)
  732	            MINTSTK=K
  733	         ELSEIF(IC(K).GT.MAXB)THEN
  734	            MAXTST=IC(K)
  735	            MAXTSTK=K
  736	         ENDIF
  737	         IF(MAXTST-MINTST.GE.IBXX2(IBITB)-LMISS)GO TO 174
  738	C           FOR THIS LOOP, LMISS = 2.
  739	         MINB=MINTST
  740	         MAXB=MAXTST
  741	         MINBK=MINTSTK
  742	         MAXBK=MAXTSTK
  743	         MISLLB=0
  744	C           WHEN THE POINT IS NON MISSING, MISLLB SET = 0.
  745	 1729    KOUNTA=KOUNTA-1
  746	C           THERE IS ONE LESS POINT NOW IN A.
  747	 173     CONTINUE  
  748	C
  749	      ENDIF
  750	C
  751	C        AT THIS POINT, KOUNTA CONTAINS THE NUMBER OF POINTS TO CLOSE
  752	C        OUT GROUP A WITH.  GROUP B NOW STARTS WITH KSTART+KOUNTA AND
  753	C        ENDS WITH NENDB.  MINB AND MAXB HAVE BEEN ADJUSTED AS
  754	C        NECESSARY TO REFLECT GROUP B (EVEN THOUGH THE NUMBER OF BITS
  755	C        NEEDED TO PACK GROUP B HAVE NOT INCREASED, THE END POINTS
  756	C        OF THE RANGE MAY HAVE).
  757	C
  758	 174  IF(KOUNTA.EQ.KOUNTS)GO TO 200
  759	C        ON TRANSFER, GROUP A WAS NOT CHANGED.  CLOSE IT OUT.
  760	C
  761	C        ONE OR MORE POINTS WERE TAKEN OUT OF A.  RANGE AND IBITA
  762	C        MAY HAVE TO BE RECOMPUTED; IBITA COULD BE LESS THAN
  763	C        ORIGINALLY COMPUTED.  IN FACT, GROUP A CAN NOW CONTAIN
  764	C        ONLY ONE POINT AND BE PACKED WITH ZERO BITS
  765	C        (UNLESS MISSS NE 0).
  766	C
  767	      NOUTA=KOUNTS-KOUNTA
  768	      KTOTAL=KTOTAL-NOUTA
  769	      KOUNTB=KOUNTB+NOUTA
  770	      IF(NENDA-NOUTA.GT.MINAK.AND.NENDA-NOUTA.GT.MAXAK)GO TO 200
  771	C        WHEN THE ABOVE TEST IS MET, THE MIN AND MAX OF THE 
  772	C        CURRENT GROUP A WERE WITHIN THE OLD GROUP A, SO THE
  773	C        RANGE AND IBITA DO NOT NEED TO BE RECOMPUTED.
  774	C        NOTE THAT MINAK AND MAXAK ARE NO LONGER NEEDED.
  775	      IBITA=0
  776	      MINA=MALLOW
  777	      MAXA=-MALLOW
  778	C
  779	C        USE SEPARATE LOOPS FOR MISSING AND NO MISSING VALUES
  780	C        FOR EFFICIENCY.
  781	C
  782	      IF(IS5(23).EQ.0)THEN
  783	C 
  784	         DO 1742 K=KSTART,NENDA-NOUTA
  785	         IF(IC(K).LT.MINA)THEN
  786	            MINA=IC(K)
  787	         ENDIF
  788	         IF(IC(K).GT.MAXA)THEN
  789	            MAXA=IC(K)
  790	         ENDIF
  791	 1742    CONTINUE
  792	C
  793	      ELSEIF(IS5(23).EQ.1)THEN 
  794	C
  795	         DO 1744 K=KSTART,NENDA-NOUTA
  796	         IF(IC(K).EQ.MISSP)GO TO 1744
  797	         IF(IC(K).LT.MINA)THEN
  798	            MINA=IC(K)
  799	         ENDIF
  800	         IF(IC(K).GT.MAXA)THEN
  801	            MAXA=IC(K)
  802	         ENDIF
  803	 1744    CONTINUE
  804	C
  805	      ELSE 
  806	C
  807	         DO 175 K=KSTART,NENDA-NOUTA
  808	         IF(IC(K).EQ.MISSP.OR.IC(K).EQ.MISSS)GO TO 175
  809	         IF(IC(K).LT.MINA)THEN
  810	            MINA=IC(K)
  811	         ENDIF
  812	         IF(IC(K).GT.MAXA)THEN
  813	            MAXA=IC(K)
  814	         ENDIF
  815	 175     CONTINUE
  816	C
  817	      ENDIF
  818	C
  819	      MISLLA=0
  820	      IF(MINA.NE.MALLOW)GO TO 1750
  821	C        ALL MISSING VALUES MUST BE ACCOMMODATED.
  822	      MINA=0
  823	      MAXA=0
  824	      MISLLA=1
  825	      IF(IS5(23).NE.2)GO TO 177
  826	C        WHEN ALL VALUES ARE MISSING AND THERE ARE NO SECONDARY
  827	C        MISSING VALUES IBITA = 0 AS ORIGINALLY SET.  OTHERWISE,
  828	C        IBITA MUST BE CALCULATED.
  829	C
  830	 1750 ITEST=MAXA-MINA+LMISS
  831	C
  832	      DO 176 IBITA=0,30
  833	      IF(ITEST.LT.IBXX2(IBITA))GO TO 177
  834	C***        THIS TEST IS THE SAME AS:
  835	C***         IF(MAXA-MINA.LT.IBXX2(IBITA)-LMISS)GO TO 177
  836	 176  CONTINUE
  837	C
  838	D     WRITE(KFILDO,1760)MAXA,MINA
  839	D1760 FORMAT(' ****ERROR IN PACK_GP.  VALUE WILL NOT PACK IN 30 BITS.',
  840	D    1       '  MAXA ='I13,'  MINA ='I13,'.  ERROR AT 1760.')
  841	      IER=706
  842	      GO TO 900
  843	C
  844	 177  CONTINUE
  845	      GO TO 200
  846	C
  847	C        *************************************
  848	C
  849	C        AT THIS POINT, GROUP B REQUIRES AS MANY BITS TO PACK AS GROUPA.
  850	C        THEREFORE, TRY TO ADD INC POINTS TO GROUP A WITHOUT INCREASING
  851	C        IBITA.  THIS AUGMENTED GROUP IS CALLED GROUP C.
  852	C
  853	C        *************************************
  854	C
  855	 180  IF(MISLLA.EQ.1)THEN
  856	         MINC=MALLOW
  857	         MINCK=MALLOW
  858	         MAXC=-MALLOW
  859	         MAXCK=-MALLOW
  860	      ELSE
  861	         MINC=MINA
  862	         MAXC=MAXA
  863	         MINCK=MINAK
  864	         MAXCK=MINAK
  865	      ENDIF
  866	C
  867	      NOUNT=0
  868	      IF(NXY-(KTOTAL+KINC).LE.LMINPK/2)KINC=NXY-KTOTAL
  869	C        ABOVE STATEMENT CONSTRAINS THE LAST GROUP TO BE NOT LESS THAN
  870	C        LMINPK/2 IN SIZE.  IF A PROVISION LIKE THIS IS NOT INCLUDED,
  871	C        THERE WILL MANY TIMES BE A VERY SMALL GROUP AT THE END.
  872	C
  873	C        USE SEPARATE LOOPS FOR MISSING AND NO MISSING VALUES
  874	C        FOR EFFICIENCY.  SINCE KINC IS USUALLY 1, USING SEPARATE
  875	C        LOOPS HERE DOESN'T BUY MUCH.  A MISSING VALUE WILL ALWAYS
  876	C        TRANSFER BACK TO GROUP A.
  877	C
  878	      IF(IS5(23).EQ.0)THEN
  879	C
  880	         DO 185 K=KTOTAL+1,MIN(KTOTAL+KINC,NXY)
  881	         IF(IC(K).LT.MINC)THEN
  882	            MINC=IC(K)
  883	            MINCK=K
  884	         ENDIF
  885	         IF(IC(K).GT.MAXC)THEN
  886	            MAXC=IC(K)
  887	            MAXCK=K
  888	         ENDIF
  889	         NOUNT=NOUNT+1
  890	 185     CONTINUE
  891	C
  892	      ELSEIF(IS5(23).EQ.1)THEN
  893	C
  894	         DO 187 K=KTOTAL+1,MIN(KTOTAL+KINC,NXY)
  895	         IF(IC(K).EQ.MISSP)GO TO 186
  896	         IF(IC(K).LT.MINC)THEN
  897	            MINC=IC(K)
  898	            MINCK=K
  899	         ENDIF
  900	         IF(IC(K).GT.MAXC)THEN
  901	            MAXC=IC(K)
  902	            MAXCK=K
  903	         ENDIF
  904	 186     NOUNT=NOUNT+1
  905	 187     CONTINUE
  906	C
  907	      ELSE
  908	C
  909	         DO 190 K=KTOTAL+1,MIN(KTOTAL+KINC,NXY)
  910	         IF(IC(K).EQ.MISSP.OR.IC(K).EQ.MISSS)GO TO 189
  911	         IF(IC(K).LT.MINC)THEN
  912	            MINC=IC(K)
  913	            MINCK=K
  914	         ENDIF
  915	         IF(IC(K).GT.MAXC)THEN
  916	            MAXC=IC(K)
  917	            MAXCK=K
  918	         ENDIF
  919	 189     NOUNT=NOUNT+1
  920	 190     CONTINUE
  921	C
  922	      ENDIF
  923	C
  924	C***D     WRITE(KFILDO,191)KOUNTA,KTOTAL,MINA,MAXA,IBITA,MISLLA,
  925	C***D    1   MINC,MAXC,NOUNT,IC(KTOTAL),IC(KTOTAL+1)
  926	C***D191  FORMAT(' AT 191, KOUNTA ='I8,'  KTOTAL ='I8,'  MINA ='I8,
  927	C***D    1       '  MAXA ='I8,'  IBITA ='I3,'  MISLLA ='I3,
  928	C***D    2       '  MINC ='I8,'  MAXC ='I8,
  929	C***D    3       '  NOUNT ='I5,'  IC(KTOTAL) ='I9,'  IC(KTOTAL+1) =',I9) 
  930	C
  931	C        IF THE NUMBER OF BITS NEEDED FOR GROUP C IS GT IBITA,
  932	C        THEN THIS GROUP A IS A GROUP TO PACK.
  933	C
  934	      IF(MINC.EQ.MALLOW)THEN
  935	         MINC=MINA
  936	         MAXC=MAXA
  937	         MINCK=MINAK
  938	         MAXCK=MAXAK
  939	         MISLLC=1
  940	         GO TO 195
  941	C           WHEN THE NEW VALUE(S) ARE MISSING, THEY CAN ALWAYS
  942	C           BE ADDED.
  943	C
  944	      ELSE
  945	         MISLLC=0
  946	      ENDIF
  947	C
  948	      IF(MAXC-MINC.GE.IBXX2(IBITA)-LMISS) GO TO 200
  949	C
  950	C        THE BITS NECESSARY FOR GROUP C HAS NOT INCREASED FROM THE
  951	C        BITS NECESSARY FOR GROUP A.  ADD THIS POINT(S) TO GROUP A.
  952	C        COMPUTE THE NEXT GROUP B, ETC., UNLESS ALL POINTS HAVE BEEN
  953	C        USED.
  954	C 
  955	 195  KTOTAL=KTOTAL+NOUNT
  956	      KOUNTA=KOUNTA+NOUNT
  957	      MINA=MINC
  958	      MAXA=MAXC
  959	      MINAK=MINCK
  960	      MAXAK=MAXCK
  961	      MISLLA=MISLLC
  962	      ADDA=.TRUE.
  963	      IF(KTOTAL.GE.NXY)GO TO 200
  964	C
  965	      IF(MINBK.GT.KTOTAL.AND.MAXBK.GT.KTOTAL)THEN
  966	         MSTART=NENDB+1
  967	C           THE MAX AND MIN OF GROUP B WERE NOT FROM THE POINTS
  968	C           REMOVED, SO THE WHOLE GROUP DOES NOT HAVE TO BE LOOKED
  969	C           AT TO DETERMINE THE NEW MAX AND MIN.  RATHER START
  970	C           JUST BEYOND THE OLD NENDB.
  971	         IBITBS=IBITB
  972	         NENDB=1
  973	         GO TO 150
  974	      ELSE
  975	         GO TO 140
  976	      ENDIF
  977	C
  978	C        *************************************
  979	C
  980	C        GROUP A IS TO BE PACKED.  STORE VALUES IN JMIN( ), JMAX( ),
  981	C        LBIT( ), AND NOV( ).
  982	C
  983	C        *************************************
  984	C
  985	 200  LX=LX+1
  986	      IF(LX.LE.NDG)GO TO 205
  987	      LMINPK=LMINPK+LMINPK/2
  988	D     WRITE(KFILDO,201)NDG,LMINPK,LX
  989	D201  FORMAT(' ****NDG ='I5,' NOT LARGE ENOUGH.',
  990	D    1       '  LMINPK IS INCREASED TO 'I3,' FOR THIS FIELD.'/
  991	D    2       '  LX = 'I10)
  992	      IERSAV=716
  993	      GO TO 105
  994	C
  995	 205  JMIN(LX)=MINA
  996	      JMAX(LX)=MAXA
  997	      LBIT(LX)=IBITA
  998	      NOV(LX)=KOUNTA
  999	      KSTART=KTOTAL+1
 1000	C
 1001	      IF(MISLLA.EQ.0)THEN
 1002	         MISSLX(LX)=MALLOW
 1003	      ELSE
 1004	         MISSLX(LX)=IC(KTOTAL)
 1005	C           IC(KTOTAL) WAS THE LAST VALUE PROCESSED.  IF MISLLA NE 0,
 1006	C           THIS MUST BE THE MISSING VALUE FOR THIS GROUP.
 1007	      ENDIF
 1008	C
 1009	C***D     WRITE(KFILDO,206)MISLLA,IC(KTOTAL),KTOTAL,LX,JMIN(LX),JMAX(LX),
 1010	C***D    1                 LBIT(LX),NOV(LX),MISSLX(LX)
 1011	C***D206  FORMAT(' AT 206,  MISLLA ='I2,'  IC(KTOTAL) ='I5,'  KTOTAL ='I8,
 1012	C***D    1       '  LX ='I6,'  JMIN(LX) ='I8,'  JMAX(LX) ='I8,
 1013	C***D    2       '  LBIT(LX) ='I5,'  NOV(LX) ='I8,'  MISSLX(LX) =',I7) 
 1014	C
 1015	      IF(KTOTAL.GE.NXY)GO TO 209
 1016	C
 1017	C        THE NEW GROUP A WILL BE THE PREVIOUS GROUP B.  SET LIMITS, ETC.
 1018	C
 1019	      IBITA=IBITB
 1020	      MINA=MINB
 1021	      MAXA=MAXB
 1022	      MINAK=MINBK
 1023	      MAXAK=MAXBK
 1024	      MISLLA=MISLLB
 1025	      NENDA=NENDB
 1026	      KOUNTA=KOUNTB
 1027	      KTOTAL=KTOTAL+KOUNTA
 1028	      ADDA=.FALSE.
 1029	      GO TO 133
 1030	C
 1031	C        *************************************
 1032	C
 1033	C        CALCULATE IBIT, THE NUMBER OF BITS NEEDED TO HOLD THE GROUP
 1034	C        MINIMUM VALUES.
 1035	C
 1036	C        *************************************
 1037	C
 1038	 209  IBIT=0
 1039	C
 1040	      DO 220 L=1,LX
 1041	 210  IF(JMIN(L).LT.IBXX2(IBIT))GO TO 220
 1042	      IBIT=IBIT+1
 1043	      GO TO 210
 1044	 220  CONTINUE
 1045	C
 1046	C        INSERT THE VALUE IN JMIN( ) TO BE USED FOR ALL MISSING
 1047	C        VALUES WHEN LBIT( ) = 0.  WHEN SECONDARY MISSING 
 1048	C        VALUES CAN BE PRESENT, LBIT(L) WILL NOT = 0.
 1049	C
 1050	      IF(IS5(23).EQ.1)THEN
 1051	C
 1052	         DO 226 L=1,LX
 1053	C   
 1054	         IF(LBIT(L).EQ.0)THEN
 1055	C
 1056	            IF(MISSLX(L).EQ.MISSP)THEN
 1057	               JMIN(L)=IBXX2(IBIT)-1
 1058	            ENDIF
 1059	C
 1060	         ENDIF
 1061	C
 1062	 226     CONTINUE
 1063	C
 1064	      ENDIF
 1065	C
 1066	C        *************************************
 1067	C
 1068	C        CALCULATE JBIT, THE NUMBER OF BITS NEEDED TO HOLD THE BITS
 1069	C        NEEDED TO PACK THE VALUES IN THE GROUPS.  BUT FIND AND
 1070	C        REMOVE THE REFERENCE VALUE FIRST.
 1071	C
 1072	C        *************************************
 1073	C
 1074	D     WRITE(KFILDO,228)CFEED,LX
 1075	D228  FORMAT(A1,/' *****************************************'
 1076	D    1          /' THE GROUP WIDTHS LBIT( ) FOR ',I8,' GROUPS'
 1077	D    2          /' *****************************************')
 1078	D     WRITE(KFILDO,229) (LBIT(J),J=1,MIN(LX,100))
 1079	D229  FORMAT(/' '20I6)
 1080	C
 1081	      LBITREF=LBIT(1)
 1082	C
 1083	      DO 230 K=1,LX
 1084	      IF(LBIT(K).LT.LBITREF)LBITREF=LBIT(K)
 1085	 230  CONTINUE
 1086	C
 1087	      IF(LBITREF.NE.0)THEN
 1088	C
 1089	         DO 240 K=1,LX
 1090	         LBIT(K)=LBIT(K)-LBITREF
 1091	 240     CONTINUE
 1092	C
 1093	      ENDIF
 1094	C
 1095	D     WRITE(KFILDO,241)CFEED,LBITREF
 1096	D241  FORMAT(A1,/' *****************************************'
 1097	D    1          /' THE GROUP WIDTHS LBIT( ) AFTER REMOVING REFERENCE ',
 1098	D    2             I8,
 1099	D    3          /' *****************************************')
 1100	D     WRITE(KFILDO,242) (LBIT(J),J=1,MIN(LX,100))
 1101	D242  FORMAT(/' '20I6)
 1102	C
 1103	      JBIT=0
 1104	C
 1105	      DO 320 K=1,LX
 1106	 310  IF(LBIT(K).LT.IBXX2(JBIT))GO TO 320
 1107	      JBIT=JBIT+1
 1108	      GO TO 310
 1109	 320  CONTINUE
 1110	C
 1111	C        *************************************
 1112	C
 1113	C        CALCULATE KBIT, THE NUMBER OF BITS NEEDED TO HOLD THE NUMBER
 1114	C        OF VALUES IN THE GROUPS.  BUT FIND AND REMOVE THE
 1115	C        REFERENCE FIRST.
 1116	C
 1117	C        *************************************
 1118	C
 1119	D     WRITE(KFILDO,321)CFEED,LX
 1120	D321  FORMAT(A1,/' *****************************************'
 1121	D    1          /' THE GROUP SIZES NOV( ) FOR ',I8,' GROUPS'
 1122	D    2          /' *****************************************')
 1123	D     WRITE(KFILDO,322) (NOV(J),J=1,MIN(LX,100))
 1124	D322  FORMAT(/' '20I6)
 1125	C
 1126	      NOVREF=NOV(1)
 1127	C
 1128	      DO 400 K=1,LX
 1129	      IF(NOV(K).LT.NOVREF)NOVREF=NOV(K)
 1130	 400  CONTINUE
 1131	C
 1132	      IF(NOVREF.GT.0)THEN
 1133	C
 1134	         DO 405 K=1,LX
 1135	         NOV(K)=NOV(K)-NOVREF
 1136	 405     CONTINUE
 1137	C
 1138	      ENDIF
 1139	C
 1140	D     WRITE(KFILDO,406)CFEED,NOVREF
 1141	D406  FORMAT(A1,/' *****************************************'
 1142	D    1          /' THE GROUP SIZES NOV( ) AFTER REMOVING REFERENCE ',I8,
 1143	D    2          /' *****************************************')
 1144	D     WRITE(KFILDO,407) (NOV(J),J=1,MIN(LX,100))
 1145	D407  FORMAT(/' '20I6)
 1146	D     WRITE(KFILDO,408)CFEED
 1147	D408  FORMAT(A1,/' *****************************************'
 1148	D    1          /' THE GROUP REFERENCES JMIN( )'
 1149	D    2          /' *****************************************')
 1150	D     WRITE(KFILDO,409) (JMIN(J),J=1,MIN(LX,100))
 1151	D409  FORMAT(/' '20I6)
 1152	C
 1153	      KBIT=0
 1154	C
 1155	      DO 420 K=1,LX
 1156	 410  IF(NOV(K).LT.IBXX2(KBIT))GO TO 420
 1157	      KBIT=KBIT+1
 1158	      GO TO 410
 1159	 420  CONTINUE
 1160	C
 1161	C        DETERMINE WHETHER THE GROUP SIZES SHOULD BE REDUCED
 1162	C        FOR SPACE EFFICIENCY.
 1163	C
 1164	      IF(IRED.EQ.0)THEN
 1165	         CALL REDUCE(KFILDO,JMIN,JMAX,LBIT,NOV,LX,NDG,IBIT,JBIT,KBIT,
 1166	     1               NOVREF,IBXX2,IER)
 1167	C
 1168	         IF(IER.EQ.714.OR.IER.EQ.715)THEN
 1169	C              REDUCE HAS ABORTED.  REEXECUTE PACK_GP WITHOUT REDUCE.
 1170	C              PROVIDE FOR A NON FATAL RETURN FROM REDUCE.  
 1171	            IERSAV=IER
 1172	            IRED=1
 1173	            IER=0
 1174	            GO TO 102 
 1175	         ENDIF
 1176	C
 1177	      ENDIF         
 1178	C
 1179	D     CALL TIMPR(KFILDO,KFILDO,'END   PACK_GP        ')
 1180	      IF(IERSAV.NE.0)THEN
 1181	         IER=IERSAV
 1182	         RETURN
 1183	      ENDIF
 1184	C
 1185	 900  IF(IER.NE.0)RETURN1
 1186	C
 1187	      RETURN
 1188	      END
                                                         1028
                                                         1119  1140  1146
                                                         1057  1165
                                                         775  832  833  948  997
                                                         1019
                                                         659  691  713  737  971
                                                         1019
                                                         504  637  691  713  737
                                                         833  948  1041  1057  1106
                                                         1156  1165
                                                         407  424  426  444  445
                                                         448  449  457  458  459
                                                         462  463  471  472  473
                                                         476  477  549  578  579
                                                         586  587  595  596  597
                                                         600  601  609  610  611
                                                         614  615  684  685  687
                                                         688  705  706  707  709
                                                         710  729  730  731  733
                                                         734  785  786  788  789
                                                         796  797  798  800  801
                                                         808  809  810  812  813
                                                         881  882  885  886  895
                                                         896  897  900  901  910
                                                         911  912  915  916  1004
                                                         1165  1168  1171  1173  1181
                                                         1185
                                                         1181
                                                         400  441  454  496  544
                                                         575  592  631  680  701
                                                         782  793  825  878  892
                                                         1050
