#!/bin/sh
all:
	@echo ""
	@echo "Please run 'make -f makefile.<Platform>'"
	@echo "Thank you."
	@echo ""

clean:
	@echo ""
	@echo "Please run 'make -f makefile.<Platform>'"
	@echo "Thank you."
	@echo ""
